package fr.lps2ima.univerity.model;

// Generated 21 janv. 2014 15:51:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseStudentId generated by hbm2java
 */
@Embeddable
public class CourseStudentId implements java.io.Serializable {

	private int courseId;
	private int studentId;

	public CourseStudentId() {
	}

	public CourseStudentId(int courseId, int studentId) {
		this.courseId = courseId;
		this.studentId = studentId;
	}

	@Column(name = "course_id", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "student_id", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseStudentId))
			return false;
		CourseStudentId castOther = (CourseStudentId) other;

		return (this.getCourseId() == castOther.getCourseId())
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
