package fr.lps2ima.univerity.model;

// Generated 21 janv. 2014 15:51:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CourseStudent generated by hbm2java
 */
@Entity
@Table(name = "course_student", catalog = "university")
public class CourseStudent implements java.io.Serializable {

	private CourseStudentId id;
	private Course course;
	private Student student;

	public CourseStudent() {
	}

	public CourseStudent(CourseStudentId id, Course course, Student student) {
		this.id = id;
		this.course = course;
		this.student = student;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "courseId", column = @Column(name = "course_id", nullable = false)),
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id", nullable = false)) })
	public CourseStudentId getId() {
		return this.id;
	}

	public void setId(CourseStudentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false, insertable = false, updatable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
