package fr.lps2ima.univerity.model;

// Generated 21 janv. 2014 15:51:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "university")
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private String forname;
	private Integer age;
	private Set<CourseStudent> courseStudents = new HashSet<CourseStudent>(0);

	public Student() {
	}

	public Student(String name) {
		this.name = name;
	}

	public Student(String name, String forname, Integer age,
			Set<CourseStudent> courseStudents) {
		this.name = name;
		this.forname = forname;
		this.age = age;
		this.courseStudents = courseStudents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "forname", length = 45)
	public String getForname() {
		return this.forname;
	}

	public void setForname(String forname) {
		this.forname = forname;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<CourseStudent> getCourseStudents() {
		return this.courseStudents;
	}

	public void setCourseStudents(Set<CourseStudent> courseStudents) {
		this.courseStudents = courseStudents;
	}

}
